version: '3'
services:
  weblate:
    image: weblate/weblate
    links:
      - database
      - cache
    volumes:
      - ./weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  web:
    build: nginx
    links:
      - weblate
    ports:
      - "8001:8001"
    volumes:
      - ./weblate-data:/app/data:ro
    restart: always
    depends_on:
      - weblate
    networks:
      - proxy
      - default
  database:
    image: postgres:9.6
    env_file:
      - ./environment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: memcached:1.4
    restart: always

networks:
  proxy:
    external: true
